--[[
    File: scripts/core/lua_consts.lua

    This core script provides a comprehensive set of constants and enumerations
    for use in all other Lua scripts. It centralizes values from the C++ source
    code, making scripts more readable and easier to maintain.
]]

--------------------------------------------------------------------------------
-- Network Packet Opcodes
--------------------------------------------------------------------------------

-- Opcodes sent from the Server to the Client
GameServerOpcodes = {
    NONE = 0,
    GAME_SERVER_INIT_GAME = 10,
    GAME_SERVER_GM_ACTIONS = 11,
    GAME_SERVER_ENTER_GAME = 15,
    GAME_SERVER_LOGIN_ERROR = 20,
    GAME_SERVER_LOGIN_ADVICE = 21,
    GAME_SERVER_LOGIN_WAIT = 22,
    GAME_SERVER_ADD_CREATURE = 23,
    GAME_SERVER_PING_BACK = 29,
    GAME_SERVER_PING = 30,
    GAME_SERVER_CHALLENGE = 31,
    GAME_SERVER_DEATH = 40,
    GAME_SERVER_EXTENDED_OPCODE = 50,
    GAME_SERVER_FULL_MAP = 100,
    GAME_SERVER_MAP_TOP_ROW = 101,
    GAME_SERVER_MAP_RIGHT_ROW = 102,
    GAME_SERVER_MAP_BOTTOM_ROW = 103,
    GAME_SERVER_MAP_LEFT_ROW = 104,
    GAME_SERVER_UPDATE_TILE = 105,
    GAME_SERVER_CREATE_ON_MAP = 106,
    GAME_SERVER_CHANGE_ON_MAP = 107,
    GAME_SERVER_DELETE_ON_MAP = 108,
    GAME_SERVER_MOVE_CREATURE = 109,
    GAME_SERVER_OPEN_CONTAINER = 110,
    GAME_SERVER_CLOSE_CONTAINER = 111,
    GAME_SERVER_CREATE_CONTAINER = 112,
    GAME_SERVER_CHANGE_IN_CONTAINER = 113,
    GAME_SERVER_DELETE_IN_CONTAINER = 114,
    GAME_SERVER_SET_INVENTORY = 120,
    GAME_SERVER_DELETE_INVENTORY = 121,
    GAME_SERVER_OPEN_NPC_TRADE = 122,
    GAME_SERVER_PLAYER_GOODS = 123,
    GAME_SERVER_CLOSE_NPC_TRADE = 124,
    GAME_SERVER_OWN_TRADE = 125,
    GAME_SERVER_COUNTER_TRADE = 126,
    GAME_SERVER_CLOSE_TRADE = 127,
    GAME_SERVER_AMBIENT = 130,
    GAME_SERVER_GRAPHICAL_EFFECT = 131,
    GAME_SERVER_TEXT_EFFECT = 132,
    GAME_SERVER_MISSLE_EFFECT = 133,
    GAME_SERVER_MARK_CREATURE = 134,
    GAME_SERVER_TRAPPERS = 135,
    GAME_SERVER_CREATURE_HEALTH = 140,
    GAME_SERVER_CREATURE_LIGHT = 141,
    GAME_SERVER_CREATURE_OUTFIT = 142,
    GAME_SERVER_CREATURE_SPEED = 143,
    GAME_SERVER_CREATURE_SKULL = 144,
    GAME_SERVER_CREATURE_PARTY = 145,
    GAME_SERVER_CREATURE_UNPASS = 146,
    GAME_SERVER_EDIT_TEXT = 150,
    GAME_SERVER_EDIT_LIST = 151,
    GAME_SERVER_PLAYER_DATA_BASIC = 159,
    GAME_SERVER_PLAYER_DATA = 160,
    GAME_SERVER_PLAYER_SKILLS = 161,
    GAME_SERVER_PLAYER_STATE = 162,
    GAME_SERVER_CLEAR_TARGET = 163,
    GAME_SERVER_SPELL_DELAY = 164,
    GAME_SERVER_SPELL_GROUP_DELAY = 165,
    GAME_SERVER_MULTI_USE_DELAY = 166,
    GAME_SERVER_TALK = 170,
    GAME_SERVER_CHANNELS = 171,
    GAME_SERVER_OPEN_CHANNEL = 172,
    GAME_SERVER_OPEN_PRIVATE_CHANNEL = 173,
    GAME_SERVER_RULE_VIOLATION_CHANNEL = 174,
    GAME_SERVER_RULE_VIOLATION_REMOVE = 175,
    GAME_SERVER_RULE_VIOLATION_CANCEL = 176,
    GAME_SERVER_RULE_VIOLATION_LOCK = 177,
    GAME_SERVER_OPEN_OWN_CHANNEL = 178,
    GAME_SERVER_CLOSE_CHANNEL = 179,
    GAME_SERVER_TEXT_MESSAGE = 180,
    GAME_SERVER_CANCEL_WALK = 181,
    GAME_SERVER_WALK_WAIT = 182,
    GAME_SERVER_UNJUSTIFIED_POINTS = 183,
    GAME_SERVER_FLOOR_CHANGE_UP = 190,
    GAME_SERVER_FLOOR_CHANGE_DOWN = 191,
    GAME_SERVER_CHOOSE_OUTFIT = 200,
    GAME_SERVER_VIP_ADD = 210,
    GAME_SERVER_VIP_LOGIN = 211,
    GAME_SERVER_VIP_LOGOUT = 212,
    GAME_SERVER_TUTORIAL_HINT = 220,
    GAME_SERVER_AUTOMAP_FLAG = 221,
    GAME_SERVER_COIN_BALANCE = 223,
    GAME_SERVER_STORE_ERROR = 224,
    GAME_SERVER_REQUEST_PURCHASE_DATA = 225,
    GAME_SERVER_QUEST_LOG = 240,
    GAME_SERVER_QUEST_LINE = 241,
    GAME_SERVER_COIN_BALANCE_UPDATING = 242,
    GAME_SERVER_CHANNEL_EVENT = 243,
    GAME_SERVER_ITEM_INFO = 244,
    GAME_SERVER_PLAYER_INVENTORY = 245,
    GAME_SERVER_MARKET_ENTER = 246,
    GAME_SERVER_MARKET_LEAVE = 247,
    GAME_SERVER_MARKET_DETAIL = 248,
    GAME_SERVER_MARKET_BROWSE = 249,
    GAME_SERVER_SHOW_MODAL_DIALOG = 250,
    GAME_SERVER_STORE = 251,
    GAME_SERVER_STORE_OFFERS = 252,
    GAME_SERVER_STORE_TRANSACTION_HISTORY = 253,
    GAME_SERVER_STORE_COMPLETE_PURCHASE = 254
}

-- Opcodes sent from the Client to the Server
ClientOpcodes = {
    CLIENT_ENTER_ACCOUNT = 1,
    CLIENT_PENDING_GAME = 10,
    CLIENT_ENTER_GAME = 15,
    CLIENT_LEAVE_GAME = 20,
    CLIENT_PING = 29,
    CLIENT_PING_BACK = 30,
    CLIENT_FIRST_GAME_OPCODE = 50,
    CLIENT_EXTENDED_OPCODE = 50,
    CLIENT_CHANGE_MAP_AWARE_RANGE = 51,
    CLIENT_AUTO_WALK = 100,
    CLIENT_WALK_NORTH = 101,
    CLIENT_WALK_EAST = 102,
    CLIENT_WALK_SOUTH = 103,
    CLIENT_WALK_WEST = 104,
    CLIENT_STOP = 105,
    CLIENT_WALK_NORTH_EAST = 106,
    CLIENT_WALK_SOUTH_EAST = 107,
    CLIENT_WALK_SOUTH_WEST = 108,
    CLIENT_WALK_NORTH_WEST = 109,
    CLIENT_TURN_NORTH = 111,
    CLIENT_TURN_EAST = 112,
    CLIENT_TURN_SOUTH = 113,
    CLIENT_TURN_WEST = 114,
    CLIENT_EQUIP_ITEM = 119,
    CLIENT_MOVE = 120,
    CLIENT_INSPECT_NPC_TRADE = 121,
    CLIENT_BUY_ITEM = 122,
    CLIENT_SELL_ITEM = 123,
    CLIENT_CLOSE_NPC_TRADE = 124,
    CLIENT_REQUEST_TRADE = 125,
    CLIENT_INSPECT_TRADE = 126,
    CLIENT_ACCEPT_TRADE = 127,
    CLIENT_REJECT_TRADE = 128,
    CLIENT_USE_ITEM = 130,
    CLIENT_USE_ITEM_WITH = 131,
    CLIENT_USE_ON_CREATURE = 132,
    CLIENT_ROTATE_ITEM = 133,
    CLIENT_CLOSE_CONTAINER = 135,
    CLIENT_UP_CONTAINER = 136,
    CLIENT_EDIT_TEXT = 137,
    CLIENT_EDIT_LIST = 138,
    CLIENT_LOOK = 140,
    CLIENT_LOOK_CREATURE = 141,
    CLIENT_QUICK_LOOT = 143,
    CLIENT_TALK = 150,
    CLIENT_REQUEST_CHANNELS = 151,
    CLIENT_JOIN_CHANNEL = 152,
    CLIENT_LEAVE_CHANNEL = 153,
    CLIENT_OPEN_PRIVATE_CHANNEL = 154,
    CLIENT_OPEN_RULE_VIOLATION = 155,
    CLIENT_CLOSE_RULE_VIOLATION = 156,
    CLIENT_CANCEL_RULE_VIOLATION = 157,
    CLIENT_CLOSE_NPC_CHANNEL = 158,
    CLIENT_CHANGE_FIGHT_MODES = 160,
    CLIENT_ATTACK = 161,
    CLIENT_FOLLOW = 162,
    CLIENT_INVITE_TO_PARTY = 163,
    CLIENT_JOIN_PARTY = 164,
    CLIENT_REVOKE_INVITATION = 165,
    CLIENT_PASS_LEADERSHIP = 166,
    CLIENT_LEAVE_PARTY = 167,
    CLIENT_SHARE_EXPERIENCE = 168,
    CLIENT_DISBAND_PARTY = 169,
    CLIENT_OPEN_OWN_CHANNEL = 170,
    CLIENT_INVITE_TO_OWN_CHANNEL = 171,
    CLIENT_EXCLUDE_FROM_OWN_CHANNEL = 172,
    CLIENT_CANCEL_ATTACK_AND_FOLLOW = 190,
    CLIENT_UPDATE_TILE = 201,
    CLIENT_REFRESH_CONTAINER = 202,
    CLIENT_BROWSE_FIELD = 203,
    CLIENT_SEEK_IN_CONTAINER = 204,
    CLIENT_REQUEST_OUTFIT = 210,
    CLIENT_CHANGE_OUTFIT = 211,
    CLIENT_MOUNT = 212,
    CLIENT_ADD_VIP = 220,
    CLIENT_REMOVE_VIP = 221,
    CLIENT_EDIT_VIP = 222,
    CLIENT_BUG_REPORT = 230,
    CLIENT_RULE_VIOLATION = 231,
    CLIENT_DEBUG_REPORT = 232,
    CLIENT_TRANSFER_COINS = 239,
    CLIENT_REQUEST_QUEST_LOG = 240,
    CLIENT_REQUEST_QUEST_LINE = 241,
    CLIENT_NEW_RULE_VIOLATION = 242,
    CLIENT_REQUEST_ITEM_INFO = 243,
    CLIENT_MARKET_LEAVE = 244,
    CLIENT_MARKET_BROWSE = 245,
    CLIENT_MARKET_CREATE = 246,
    CLIENT_MARKET_CANCEL = 247,
    CLIENT_MARKET_ACCEPT = 248,
    CLIENT_ANSWER_MODAL_DIALOG = 249,
    CLIENT_OPEN_STORE = 250,
    CLIENT_REQUEST_STORE_OFFERS = 251,
    CLIENT_BUY_STORE_OFFER = 252,
    CLIENT_OPEN_TRANSACTION_HISTORY = 253,
    CLIENT_REQUEST_TRANSACTION_HISTORY = 254
}

-- Current protocol additions are deliberately kept separate from the legacy
-- tables above. Some bytes have different meanings in different Tibia
-- protocol profiles; duplicate values below are intentional aliases.
CurrentClientOpcodes = {
    CLIENT_STASH_WITHDRAW = 0x28,
    CLIENT_RETRIEVE_DEPOT_SEARCH = 0x29,
    CLIENT_CYCLOPEDIA_MONSTER_TRACKER = 0x2A,
    CLIENT_PARTY_ANALYZER_ACTION = 0x2B,
    CLIENT_LEADER_FINDER_WINDOW = 0x2C,
    CLIENT_MEMBER_FINDER_WINDOW = 0x2D,
    CLIENT_SET_CLIENT_OPTIONS = 0x2E,
    CLIENT_PLAYER_TYPING = 0x38,
    CLIENT_TASK_BOARD = 0x5F,
    CLIENT_INVENTORY_IMBUEMENTS = 0x60,
    CLIENT_OPEN_WHEEL = 0x61,
    CLIENT_SAVE_WHEEL = 0x62,
    CLIENT_CHECK = 0x63,
    CLIENT_SET_VOCATION = 0x6E,
    CLIENT_TELEPORT = 0x73,
    CLIENT_OFFLINE_TRAINING = 0x74,
    CLIENT_CONTAINER_ACTION = 0x75,
    CLIENT_CHARACTER_TRADE_CONFIGURATION = 0x76,
    CLIENT_FRIEND_SYSTEM_ACTION = 0x81,
    CLIENT_CONFIGURE_SHOW_OFF_SOCKET = 0x86,
    CLIENT_WRAPABLE_ITEM = 0x8B,
    CLIENT_JOIN_AGGRESSION = 0x8E,
    CLIENT_LOOT_CONTAINER = 0x90,
    CLIENT_QUICK_LOOT_BLACK_WHITELIST = 0x91,
    CLIENT_OPEN_DEPOT_SEARCH = 0x92,
    CLIENT_CLOSE_DEPOT_SEARCH = 0x93,
    CLIENT_DEPOT_SEARCH_ITEM_REQUEST = 0x94,
    CLIENT_OPEN_PARENT_CONTAINER = 0x95,
    CLIENT_EDIT_GUILD_MESSAGE = 0x9C,
    CLIENT_GET_TEXT_FOR_REPORT = 0x9D,
    CLIENT_SET_MONSTER_PODIUM = 0x9F,
    CLIENT_CYCLOPEDIA_HOUSE_AUCTION = 0xAD,
    CLIENT_BOSSTIARY = 0xAE,
    CLIENT_BOSSTIARY_SLOTS = 0xAF,
    CLIENT_BOSSTIARY_SLOT = 0xB0,
    CLIENT_HIGHSCORES = 0xB1,
    CLIENT_IMBUEMENT_ACTION = 0xB2,
    CLIENT_WEAPON_PROFICIENCY = 0xB3,
    CLIENT_TASK_HUNTING_ACTION = 0xBA,
    CLIENT_SOUL_SEALS_FIGHT_MONSTER = 0xBA,
    CLIENT_FORGE_ENTER = 0xBF,
    CLIENT_FORGE_HISTORY = 0xC0,
    CLIENT_DETAILS = 0xC1,
    CLIENT_BOSS_DIFFICULTY = 0xC2,
    CLIENT_AIM_AT_TARGET = 0xC8,
    CLIENT_TRANSACTION_DETAILS = 0xC9,
    CLIENT_EXIVA_RESTRICTIONS = 0xCA,
    CLIENT_INSPECT_OBJECT = 0xCD,
    CLIENT_INSPECT_PLAYER = 0xCE,
    CLIENT_BLESSING_WINDOW = 0xCF,
    CLIENT_REQUEST_TRACKER_QUEST_LOG = 0xD0,
    CLIENT_APPLY_IMBUEMENT = 0xD5,
    CLIENT_CLEAR_IMBUEMENT = 0xD6,
    CLIENT_CLOSE_IMBUEMENT = 0xD7,
    CLIENT_OPEN_REWARD_WALL = 0xD8,
    CLIENT_OPEN_REWARD_HISTORY = 0xD9,
    CLIENT_GET_DAILY_REWARD = 0xDA,
    CLIENT_CYCLOPEDIA_MAP_ACTION = 0xDB,
    CLIENT_VIP_GROUP_ACTIONS = 0xDF,
    CLIENT_BESTIARY_RACES = 0xE1,
    CLIENT_BESTIARY_CREATURES = 0xE2,
    CLIENT_BESTIARY_MONSTER_DATA = 0xE3,
    CLIENT_BUY_CHARM_RUNE = 0xE4,
    CLIENT_CYCLOPEDIA_CHARACTER_INFO = 0xE5,
    CLIENT_WHEEL_GEM_ACTION = 0xE7,
    CLIENT_OFFER_DESCRIPTION = 0xE8,
    CLIENT_PREY_ACTION = 0xEB,
    CLIENT_SET_HIRELING_NAME = 0xEC,
    CLIENT_PREY_REQUEST = 0xED,
    CLIENT_RESOURCE_BALANCE = 0xED,
    CLIENT_GREET = 0xEE,
    CLIENT_REWARD_CHEST_COLLECT = 0xFF
}

CurrentGameServerOpcodes = {
    GAME_SERVER_ALLOW_BUG_REPORT = 0x1A,
    GAME_SERVER_OPEN_STASH = 0x29,
    GAME_SERVER_SPECIAL_CONTAINERS_AVAILABLE = 0x2A,
    GAME_SERVER_PARTY_ANALYZER = 0x2B,
    GAME_SERVER_LEADER_TEAM_FINDER = 0x2C,
    GAME_SERVER_TEAM_FINDER_LIST = 0x2D,
    GAME_SERVER_TASK_BOARD = 0x5B,
    GAME_SERVER_WEAPON_PROFICIENCY_EXPERIENCE = 0x5C,
    GAME_SERVER_IMBUEMENT_DURATIONS = 0x5D,
    GAME_SERVER_PASSIVE_COOLDOWN = 0x5E,
    GAME_SERVER_OPEN_WHEEL = 0x5F,
    GAME_SERVER_INVENTORY_IMBUEMENTS = 0x60,
    GAME_SERVER_BOSSTIARY_DATA = 0x61,
    GAME_SERVER_BOSSTIARY_SLOTS = 0x62,
    GAME_SERVER_CLIENT_CHECK = 0x63,
    GAME_SERVER_BOSSTIARY_INFO = 0x73,
    GAME_SERVER_FRIEND_SYSTEM_DATA = 0x74,
    GAME_SERVER_TAKE_SCREENSHOT = 0x75,
    GAME_SERVER_CYCLOPEDIA_ITEM_DETAIL = 0x76,
    GAME_SERVER_ITEM_INSPECTION = 0x77,
    GAME_SERVER_CHARACTER_TRADE_CONFIGURATION = 0x80,
    GAME_SERVER_REPORT_TEXT_UI = 0x81,
    GAME_SERVER_ITEM_CLASSES = 0x86,
    GAME_SERVER_OPEN_FORGE = 0x87,
    GAME_SERVER_FORGE_HISTORY = 0x88,
    GAME_SERVER_CLOSE_FORGE = 0x89,
    GAME_SERVER_FORGE_RESULT = 0x8A,
    GAME_SERVER_CREATURE_DATA = 0x8B,
    GAME_SERVER_CREATURE_ICON = 0x8B,
    GAME_SERVER_CREATURE_MARKS = 0x93,
    GAME_SERVER_CREATURE_HELPERS = 0x94,
    GAME_SERVER_DEPOT_ITEMS = 0x94,
    GAME_SERVER_CREATURE_TYPE = 0x95,
    GAME_SERVER_GAME_NEWS = 0x98,
    GAME_SERVER_DEPOT_SEARCH_DETAIL = 0x99,
    GAME_SERVER_CLOSE_DEPOT_SEARCH = 0x9A,
    GAME_SERVER_BLESSING_WINDOW = 0x9B,
    GAME_SERVER_BLESSING_STATUS = 0x9C,
    GAME_SERVER_PRESET = 0x9D,
    GAME_SERVER_PREMIUM_TRIGGER = 0x9E,
    GAME_SERVER_FIGHT_MODES = 0xA7,
    GAME_SERVER_PLAYER_MODES = 0xA7,
    GAME_SERVER_DEEP_LINK = 0xA8,
    GAME_SERVER_RESTING_STATUS = 0xA9,
    GAME_SERVER_EXPERIENCE_TRACKER = 0xAF,
    GAME_SERVER_HIGHSCORES = 0xB1,
    GAME_SERVER_PVP_SITUATIONS = 0xB8,
    GAME_SERVER_BESTIARY_REFRESH_TRACKER = 0xB9,
    GAME_SERVER_TASK_HUNTING_BASIC_DATA = 0xBA,
    GAME_SERVER_SOUL_SEALS_WINDOW = 0xBA,
    GAME_SERVER_TASK_HUNTING_DATA = 0xBB,
    GAME_SERVER_BOSSTIARY_COOLDOWN = 0xBD,
    GAME_SERVER_LOOT_CONTAINERS = 0xC0,
    GAME_SERVER_MONK_DATA = 0xC1,
    GAME_SERVER_MONSTER_PODIUM = 0xC2,
    GAME_SERVER_CYCLOPEDIA_HOUSE_AUCTION = 0xC3,
    GAME_SERVER_WEAPON_PROFICIENCY_INFO = 0xC4,
    GAME_SERVER_GEM_ATELIER = 0xC5,
    GAME_SERVER_TOURNAMENT_LEADERBOARD = 0xC5,
    GAME_SERVER_CYCLOPEDIA_HOUSES_INFO = 0xC6,
    GAME_SERVER_CYCLOPEDIA_HOUSE_LIST = 0xC7,
    GAME_SERVER_EXIVA_SUPPRESSED = 0xC9,
    GAME_SERVER_EXIVA_RESTRICTIONS = 0xCA,
    GAME_SERVER_TRANSACTION_DETAILS = 0xCB,
    GAME_SERVER_IMPACT_TRACKER = 0xCC,
    GAME_SERVER_ITEMS_PRICE = 0xCD,
    GAME_SERVER_SUPPLY_TRACKER = 0xCE,
    GAME_SERVER_LOOT_TRACKER = 0xCF,
    GAME_SERVER_QUEST_TRACKER = 0xD0,
    GAME_SERVER_KILL_TRACKER = 0xD1,
    GAME_SERVER_VIP_GROUPS = 0xD4,
    GAME_SERVER_BESTIARY_RACES = 0xD5,
    GAME_SERVER_BESTIARY_OVERVIEW = 0xD6,
    GAME_SERVER_BESTIARY_MONSTER_DATA = 0xD7,
    GAME_SERVER_BESTIARY_CHARMS = 0xD8,
    GAME_SERVER_BESTIARY_ENTRY_CHANGED = 0xD9,
    GAME_SERVER_CYCLOPEDIA_CHARACTER_INFO = 0xDA,
    GAME_SERVER_HIRELING_NAME_CHANGE = 0xDB,
    GAME_SERVER_DAILY_REWARD_COLLECTION_STATE = 0xDE,
    GAME_SERVER_OPEN_REWARD_WALL = 0xE2,
    GAME_SERVER_CLOSE_REWARD_WALL = 0xE3,
    GAME_SERVER_DAILY_REWARD = 0xE4,
    GAME_SERVER_REWARD_HISTORY = 0xE5,
    GAME_SERVER_PREY_FREE_REROLLS = 0xE6,
    GAME_SERVER_BOSSTIARY_ENTRY_CHANGED = 0xE6,
    GAME_SERVER_PREY_TIME = 0xE7,
    GAME_SERVER_PREY_DATA = 0xE8,
    GAME_SERVER_PREY_PRICES = 0xE9,
    GAME_SERVER_SHOW_DESCRIPTION = 0xEA,
    GAME_SERVER_IMBUEMENT_WINDOW = 0xEB,
    GAME_SERVER_CLOSE_IMBUEMENT_WINDOW = 0xEC,
    GAME_SERVER_ERROR = 0xED,
    GAME_SERVER_IMBUEMENT_RESULT = 0xED,
    GAME_SERVER_MESSAGE_DIALOG = 0xED,
    GAME_SERVER_RESOURCE_BALANCE = 0xEE,
    GAME_SERVER_TIBIA_TIME = 0xEF
}

---
-- Combat & Effects (New Additions)
---
CombatParam = {
    TYPE = 0, EFFECT = 1, DISTANCE_EFFECT = 2, BLOCK_SHIELD = 3, BLOCK_ARMOR = 4,
    TARGET_CASTER_OR_TOPMOST = 5, CREATE_ITEM = 6, AGGRESSIVE = 7, DISPEL = 8,
    USE_CHARGES = 9, CAST_SOUND = 10, IMPACT_SOUND = 11, CHAIN_EFFECT = 12
}

MagicEffectClasses = {
    NONE = 0, DRAW_BLOOD = 1, LOSE_ENERGY = 2, POFF = 3, BLOCK_HIT = 4, EXPLOSION_AREA = 5,
    EXPLOSION_HIT = 6, FIRE_AREA = 7, YELLOW_RINGS = 8, GREEN_RINGS = 9, HIT_AREA = 10,
    TELEPORT = 11, ENERGY_HIT = 12, MAGIC_BLUE = 13, MAGIC_RED = 14, MAGIC_GREEN = 15,
    HIT_BY_FIRE = 16, HIT_BY_POISON = 17, MORT_AREA = 18, SOUND_GREEN = 19, SOUND_RED = 20,
    POISON_AREA = 21, SOUND_YELLOW = 22, SOUND_PURPLE = 23, SOUND_BLUE = 24, SOUND_WHITE = 25,
    BUBBLES = 26, CRAPS = 27, GIFT_WRAPS = 28, FIREWORK_YELLOW = 29, FIREWORK_RED = 30,
    FIREWORK_BLUE = 31, STUN = 32, SLEEP = 33, WATER_CREATURE = 34, GROUND_SHAKER = 35,
    HEARTS = 36, FIRE_ATTACK = 37, ENERGY_AREA = 38, SMALL_CLOUDS = 39, HOLY_DAMAGE = 40,
    BIG_CLOUDS = 41, ICE_AREA = 42, ICE_TORNADO = 43, ICE_ATTACK = 44, STONES = 45,
    SMALL_PLANTS = 46, CARNIPHILA = 47, PURPLE_ENERGY = 48, YELLOW_ENERGY = 49, HOLY_AREA = 50,
    BIG_PLANTS = 51, CAKE = 52, GIANT_ICE = 53, WATER_SPLASH = 54, PLANT_ATTACK = 55,
    TUTORIAL_ARROW = 56, TUTORIAL_SQUARE = 57, MIRROR_HORIZONTAL = 58, MIRROR_VERTICAL = 59,
    SKULL_HORIZONTAL = 60, SKULL_VERTICAL = 61, ASSASSIN = 62, STEPS_HORIZONTAL = 63,
    BLOODY_STEPS = 64, STEPS_VERTICAL = 65, YALAHARIGHOST = 66, BATS = 67, SMOKE = 68,
    INSECTS = 69, DRAGONHEAD = 70, ORCSHAMAN = 71, ORCSHAMAN_FIRE = 72, THUNDER = 73,
    FERUMBRAS = 74, CONFETTI_HORIZONTAL = 75, CONFETTI_VERTICAL = 76, BLACK_SMOKE = 158,
    RED_SMOKE = 167, YELLOW_SMOKE = 168, GREEN_SMOKE = 169, PURPLE_SMOKE = 170,
    EARLY_THUNDER = 171, RAGIAZ_BONE_CAPSULE = 172, CRITICAL_DAMAGE = 173,
    PLUNGING_FISH = 175, BLUE_ENERGY_SPARK = 176, ORANGE_ENERGY_SPARK = 177,
    GREEN_ENERGY_SPARK = 178, PINK_ENERGY_SPARK = 179, WHITE_ENERGY_SPARK = 180,
    YELLOW_ENERGY_SPARK = 181, MAGIC_POWDER = 182, PIXIE_EXPLOSION = 184,
    PIXIE_COMING = 185, PIXIE_GOING = 186, STORM = 188, STONE_STORM = 189,
    BLUE_GHOST = 191, PINK_VORTEX = 193, TREASURE_MAP = 194, PINK_BEAM = 195,
    GREEN_FIREWORKS = 196, ORANGE_FIREWORKS = 197, PINK_FIREWORKS = 198,
    BLUE_FIREWORKS = 199, SUPREME_CUBE = 201, BLACK_BLOOD = 202,
    PRISMATIC_SPARK = 203, THAIAN = 204, THAIAN_GHOST = 205, GHOST_SMOKE = 206,
    WATER_BLOCK_FLOATING = 208, WATER_BLOCK = 209, ROOTS = 210,
    GHOSTLY_SCRATCH = 213, GHOSTLY_BITE = 214, BIG_SCRATCH = 215, SLASH = 216,
    BITE = 217, CHIVALROUS_CHALLENGE = 219, DIVINE_DAZZLE = 220,
    ELECTRICAL_SPARK = 221, PURPLE_TELEPORT = 222, RED_TELEPORT = 223,
    ORANGE_TELEPORT = 224, GREY_TELEPORT = 225, LIGHT_BLUE_TELEPORT = 226,
    FATAL = 230, DODGE = 231, HOURGLASS = 232, DAZZLING = 233, SPARKLING = 234,
    FERUMBRAS_1 = 235, GAZHARAGOTH = 236, MAD_MAGE = 237, HORESTIS = 238,
    DEVOVORGA = 239, FERUMBRAS_2 = 240, WHITE_SMOKE = 241, WHITE_SMOKES = 242,
    WATER_DROP = 243, AVATAR_APPEAR = 244, DIVINE_GRENADE = 245,
    DIVINE_EMPOWERMENT = 246, WATER_FLOATING_THRASH = 247, AGONY = 249,
    LOOT_HIGHLIGHT = 252, MELTING_CREAM = 263, REAPER = 264,
    POWERFUL_HEARTS = 265, CREAM = 266, GENTLE_BUBBLE = 267, STARBURST = 268,
    SIRUP = 269, CACAO = 270, CANDY_FLOSS = 271, HIT_AREA_GREEN = 272,
    HIT_AREA_RED = 273, HIT_AREA_BLUE = 274, HIT_AREA_ORANGE = 275,
    WHIRLWIND_BLOW_WHITE = 276, WHIRLWIND_BLOW_GREEN = 277,
    WHIRLWIND_BLOW_PINK = 278, PULSE_WHITE = 279, PULSE_GREEN = 280,
    PULSE_PINK = 281, CLAW_WHITE = 282, CLAW_GREEN = 283, CLAW_PINK = 284,
    BLOW_WHITE = 285, BLOW_GREEN = 286, BLOW_BLUE = 287, BLOW_PINK = 288,
    OUTBURST_WHITE = 289, OUTBURST_GREEN = 290, OUTBURST_YELLOW = 291,
    INK_EXPLOSION = 292, PAPER_PLANE = 293, WOODEN_STAKES = 294,
    FIRE_SPARKLES = 295, OPENING_MAGIC_BOOK = 296, GRAY_ELECTRIC_SPARK = 301,
    GREEN_ELECTRIC_SPARK = 302, PURPLE_ELECTRIC_SPARK = 303,
    LAST = 220, LAST_CURRENT = 304
}

ShootType = {
    NONE = 0, SPEAR = 1, BOLT = 2, ARROW = 3, FIRE = 4, ENERGY = 5, POISON_ARROW = 6,
    BURST_ARROW = 7, THROWING_STAR = 8, THROWING_KNIFE = 9, SMALL_STONE = 10, DEATH = 11,
    LARGE_ROCK = 12, SNOWBALL = 13, POWER_BOLT = 14, POISON = 15, INFERNAL_BOLT = 16,
    HUNTING_SPEAR = 17, ENCHANTED_SPEAR = 18, RED_STAR = 19, GREEN_STAR = 20, ROYAL_SPEAR = 21,
    SNIPER_ARROW = 22, ONYX_ARROW = 23, PIERCING_BOLT = 24, WHIRLWIND_SWORD = 25,
    WHIRLWIND_AXE = 26, WHIRLWIND_CLUB = 27, ETHEREAL_SPEAR = 28, ICE = 29, EARTH = 30,
    HOLY = 31, SUDDEN_DEATH = 32, FLASH_ARROW = 33, FLAMING_ARROW = 34, SHIVER_ARROW = 35,
    ENERGY_BALL = 36, SMALL_ICE = 37, SMALL_HOLY = 38, SMALL_EARTH = 39, EARTH_ARROW = 40,
    EXPLOSION = 41, CAKE = 42, TARSAL_ARROW = 44, VORTEX_BOLT = 45, PRISMATIC_BOLT = 48,
    CRYSTALLINE_ARROW = 49, DRILL_BOLT = 50, ENVENOMED_ARROW = 51, GLOOTH_SPEAR = 53,
    SIMPLE_ARROW = 54, LEAF_STAR = 56, DIAMOND_ARROW = 57, SPECTRAL_BOLT = 58,
    ROYAL_STAR = 59, CANDY_CANE = 61, CHERRY_BOMB = 62,
    LAST = 59, LAST_CURRENT = 62
}

MagicEffectsType = {
    END_LOOP = 0,
    DELTA = 1,
    DELAY = 2,
    CREATE_EFFECT = 3,
    CREATE_DISTANCE_EFFECT = 4,
    CREATE_DISTANCE_EFFECT_REVERSED = 5,
    CREATE_SOUND_MAIN_EFFECT = 6,
    CREATE_SOUND_SECONDARY_EFFECT = 7
}

WeaponProficiencyAction = {
    ITEM_INFO = 0,
    LIST_INFO = 1,
    RESET_PERKS = 2,
    APPLY_PERKS = 3
}

WeaponProficiencyBonus = {
    ATTACK_DAMAGE = 0,
    DEFENSE_BONUS = 1,
    WEAPON_SHIELD_MODIFIER = 2,
    SKILL_BONUS = 3,
    SPECIALIZED_MAGIC_LEVEL = 4,
    SPELL_AUGMENT = 5,
    BESTIARY = 6,
    POWERFUL_FOE_BONUS = 7,
    CRITICAL_HIT_CHANCE = 8,
    ELEMENTAL_HIT_CHANCE = 9,
    RUNE_CRITICAL_HIT_CHANCE = 10,
    AUTO_ATTACK_CRITICAL_HIT_CHANCE = 11,
    CRITICAL_EXTRA_DAMAGE = 12,
    ELEMENTAL_CRITICAL_EXTRA_DAMAGE = 13,
    RUNE_CRITICAL_EXTRA_DAMAGE = 14,
    AUTO_ATTACK_CRITICAL_EXTRA_DAMAGE = 15,
    MANA_LEECH = 16,
    LIFE_LEECH = 17,
    MANA_GAIN_ON_HIT = 18,
    LIFE_GAIN_ON_HIT = 19,
    MANA_GAIN_ON_KILL = 20,
    LIFE_GAIN_ON_KILL = 21,
    PERFECT_SHOT_DAMAGE = 22,
    RANGED_HIT_CHANCE = 23,
    ATTACK_RANGE = 24,
    SKILL_PERCENTAGE_AUTO_ATTACK = 25,
    SKILL_PERCENTAGE_SPELL_DAMAGE = 26,
    SKILL_PERCENTAGE_SPELL_HEALING = 27,
    ALPHA_STRIKE_EXTRA_DAMAGE = 28,
    OMEGA_STRIKE_EXTRA_DAMAGE = 29,
    ARMOR_PENETRATION = 30,
    ELEMENTAL_PIERCE = 31
}

WeaponProficiencySkillPercentage = {
    AUTO_ATTACK = 0,
    SPELL_DAMAGE = 1,
    SPELL_HEALING = 2
}

WeaponProficiencySpellBoost = {
    MANA = 0,
    COOLDOWN = 1,
    GROUP_COOLDOWN = 2,
    SECONDARY_GROUP_COOLDOWN = 3,
    MANA_LEECH = 4,
    MANA_LEECH_CHANCE = 5,
    LIFE_LEECH = 6,
    LIFE_LEECH_CHANCE = 7,
    DAMAGE = 8,
    DAMAGE_REDUCTION = 9,
    HEAL = 10,
    CRITICAL_DAMAGE = 11,
    CRITICAL_CHANCE = 12,
    TOTAL_COUNT = 13
}

WeaponProficiencyHealth = {
    LIFE = 0,
    MANA = 1
}

WeaponProficiencyGain = {
    HIT = 0,
    KILL = 1
}

WeaponProficiencyExperience = {
    EASY = 1,
    MEDIUM = 2,
    HARD = 3
}

ImbuementType = {
    NONE = -1,
    ELEMENTAL_DAMAGE = 0,
    LIFE_LEECH = 1,
    MANA_LEECH = 2,
    CRITICAL_HIT = 3,
    DEATH_PROTECTION = 4,
    EARTH_PROTECTION = 5,
    FIRE_PROTECTION = 6,
    ICE_PROTECTION = 7,
    ENERGY_PROTECTION = 8,
    HOLY_PROTECTION = 9,
    SPEED = 10,
    SKILL_AXE = 11,
    SKILL_SWORD = 12,
    SKILL_CLUB = 13,
    SKILL_SHIELDING = 14,
    SKILL_DISTANCE = 15,
    MAGIC_LEVEL = 16,
    CAPACITY = 17,
    SKILL_FIST = 18,
    PARALYSIS_DEFLECTION = 19
}

BestiaryRace = {
    NONE = 0,
    AMPHIBIC = 1,
    AQUATIC = 2,
    BIRD = 3,
    CONSTRUCT = 4,
    DEMON = 5,
    DRAGON = 6,
    ELEMENTAL = 7,
    FEY = 8,
    GIANT = 9,
    HUMAN = 10,
    HUMANOID = 11,
    LYCANTHROPE = 12,
    MAGICAL = 13,
    MAMMAL = 14,
    PLANT = 15,
    REPTILE = 16,
    SLIME = 17,
    UNDEAD = 18,
    VERMIN = 19,
    EXTRA_DIMENSIONAL = 20,
    INKBORN = 21
}

CharmRune = {
    NONE = -1,
    WOUND = 0,
    ENFLAME = 1,
    POISON = 2,
    FREEZE = 3,
    ZAP = 4,
    CURSE = 5,
    CRIPPLE = 6,
    PARRY = 7,
    DODGE = 8,
    ADRENALINE_BURST = 9,
    NUMB = 10,
    CLEANSE = 11,
    BLESS = 12,
    SCAVENGE = 13,
    GUT = 14,
    LOW_BLOW = 15,
    DIVINE_WRATH = 16,
    VAMPIRIC_EMBRACE = 17,
    VOID_CALL = 18,
    SAVAGE_BLOW = 19,
    FATAL_HOLD = 20,
    VOID_INVERSION = 21,
    CARNAGE = 22,
    OVERPOWER = 23,
    OVERFLUX = 24
}

---
-- Movement & Pathfinding
---
RotateDirection = { NORTH = 0, EAST = 1, SOUTH = 2, WEST = 3 }
MoveDirection = {
    NORTH = 0, EAST = 1, SOUTH = 2, WEST = 3, NORTHEAST = 5, SOUTHEAST = 6,
    SOUTHWEST = 7, NORTHWEST = 8, INVALID = 9
}
PathFindResult = {
    OK = 0, SAME_POSITION = 1, IMPOSSIBLE = 2, TOO_FAR = 3, NO_WAY = 4, GOAL_BLOCKED = 5, NONE = 6
}
PathFindFlags = {
    ALLOW_NOT_SEEN_TILES = 1, ALLOW_CREATURES = 2, ALLOW_NON_PATHABLE = 4,
    ALLOW_NON_WALKABLE = 8, IGNORE_CREATURES = 16, IGNORE_GOAL_POSITION = 32,
    CHECK_GOAL_POSITION = 64, PRIORITIZE_DIAGONAL_MOVEMENTS = 128
}

---
-- Items, Social & Avatars
---
ItemCategory = {
    NONE = 0, ARMORS = 1, AMULETS = 2, BOOTS = 3, CONTAINERS = 4, DECORATION = 5, FOOD = 6,
    HELMETS_HATS = 7, LEGS = 8, OTHERS = 9, POTIONS = 10, RINGS = 11, RUNES = 12,
    SHIELDS = 13, TOOLS = 14, VALUABLES = 15, AMMUNITION = 16, AXES = 17, CLUBS = 18,
    DISTANCE_WEAPONS = 19, SWORDS = 20, WANDS_RODS = 21, PREMIUM_SCROLLS = 22,
    TIBIA_COINS = 23, CREATURE_PRODUCTS = 24, QUIVER = 25, SOULCORES = 26
}

PartyShield = {
    NO_PARTY = 0, INVITED_BY_SOMEONE = 1, INVITED_BY_YOU = 2, MEMBER = 3, LEADER = 4,
    MEMBER_SHARED_EXP_WORKING = 5, LEADER_SHARED_EXP_WORKING = 6, MEMBER_SHARED_EXP_ACTIVATED = 7,
    LEADER_SHARED_EXP_ACTIVATED = 8, IN_PARTY_WITH_SOMEONE = 11
}

GuildShield = {
    NO_GUILD = 0, WAR_FRIEND = 1, WAR_ENEMY = 2, IN_WAR_WITH_SOMEONE = 3,
    IN_SAME_GUILD = 4, IN_DIFFERENT_GUILD = 5
}

PlayerAvatarOutfitIds = { KNIGHT = 1593, PALADIN = 1594, SORCERER = 1595, DRUID = 1596, MONK = 1833 }

---
-- Game Enumerations
---

-- Message Classes (for server text messages)
SpeakClasses = {
	TALKTYPE_SAY = 1,
	TALKTYPE_WHISPER = 2,
	TALKTYPE_YELL = 3,
	TALKTYPE_PRIVATE_FROM = 4,
	TALKTYPE_PRIVATE_TO = 5,
	TALKTYPE_CHANNEL_MANAGER = 6,
	TALKTYPE_CHANNEL_Y = 7,
	TALKTYPE_CHANNEL_O = 8,
	TALKTYPE_SPELL_USE = 9,
	TALKTYPE_PRIVATE_NP = 10,
	TALKTYPE_NPC_UNKOWN = 11,
	TALKTYPE_PRIVATE_PN = 12,
	TALKTYPE_BROADCAST = 13,
	TALKTYPE_CHANNEL_R1 = 14,
	TALKTYPE_PRIVATE_RED_FROM = 15,
	TALKTYPE_PRIVATE_RED_TO = 16,
	TALKTYPE_MONSTER_SAY = 36,
	TALKTYPE_MONSTER_YELL = 37,
	TALKTYPE_MONSTER_LAST_OLDPROTOCOL = 38,
	TALKTYPE_CHANNEL_R2 = 0xFF
}

--------------------------------------------------------------------------------
-- Game State & Player Enumerations
--------------------------------------------------------------------------------

-- Message modes for chat and game text
MessageMode = {
    WHISPER = 0,
    SAY = 1,
    YELL = 2,
    PRIVATE_FROM = 4,
    PRIVATE_TO = 5,
    CHANNEL_MANAGEMENT = 6,
    CHANNEL = 7,
    CHANNEL_HIGHLIGHT = 8,
    SPELL = 9,
    NPC_FROM = 10,
    NPC_TO = 11,
    GAMEMASTER_BROADCAST = 12,
    GAMEMASTER_CHANNEL = 13,
    GAMEMASTER_PRIVATE_FROM = 14,
    GAMEMASTER_PRIVATE_TO = 15,
    LOGIN = 16,
    WARNING = 17,
    GAME = 18,
    FAILURE = 19,
    LOOK = 20,
    DAMAGE_DEALED = 21,
    DAMAGE_RECEIVED = 22,
    HEAL = 23,
    EXP = 24,
    DAMAGE_OTHERS = 25,
    HEAL_OTHERS = 26,
    EXP_OTHERS = 27,
    STATUS = 28,
    LOOT = 29,
    TRADE_NPC = 30,
    GUILD = 31,
    PARTY_MANAGEMENT = 32,
    PARTY = 33,
    BARK_LOW = 34,
    BARK_LOUD = 35,
    REPORT = 36,
    HOTKEY_USE = 37,
    TUTORIAL_HINT = 38,
    THANKYOU = 39,
    MARKET = 40,
    MANA = 41,
    BEYOND_LAST = 42,
    MONSTER_YELL = 43,
    MONSTER_SAY = 44,
    RED = 45,
    BLUE = 46,
    RVR_CHANNEL = 47,
    RVR_ANSWER = 48,
    RVR_CONTINUE = 49,
    GAME_HIGHLIGHT = 50,
    NPC_FROM_START_BLOCK = 51,
    LAST = 52,
    INVALID = 255
}

-- Legacy message classes for server text messages
MessageClasses = {
    NONE = 0,
    STATUS_WARNING = 9,
    GAME_MASTER_CONSOLE = 13,
    LOGIN = 17,
    GAME = 18,
    FAILURE = 19,
    LOOK = 20,
    DAMAGE_DEALED = 21,
    DAMAGE_RECEIVED = 22,
    HEALED = 23,
    EXP = 24,
    DAMAGE_OTHERS = 25,
    HEAL_OTHERS = 26,
    EXP_OTHERS = 27,
    STATUS = 28,
    LOOT = 29,
    TRADE_NPC = 30,
    GUILD = 31,
    PARTY_MANAGEMENT = 32,
    PARTY = 33,
    REPORT = 36,
    HOTKEY_USE = 37,
    MANA = 41,
    MONSTER_YELL = 43,
    MONSTER_SAY = 44,
    GAME_HIGHLIGHT = 50
}

-- Screen positions for printing messages
PrintMessagePosition = {
    MIDDLE = 0,
    BOTTOM = 1,
    LOOT = 2
}

-- creature types
CreatureType = {
    PLAYER = 0,
    MONSTER = 1,
    NPC = 2,
    SUMMON_OWN = 3,
    SUMMON_OTHERS = 4,
    HIDDEN = 5
}

CooldownGroupId ={
	ATTACK = 1,
	HEALING = 2,
	SUPPORT = 3,
	SPECIAL = 4,
	CRIPPLING = 5,
	FOCUS = 7,
	ULTIMATE = 8,
	GREAT_BEAMS = 9,
	BURST_OF_NATURE = 10,
	VIRTUE = 11
};

-- Player status flags/conditions
CharacterFlag = {
    POISONED = 0,
    BURNING = 1,
    ELECTRIFIED = 2,
    DRUNK = 3,
    MANA_SHIELDED = 4,
    PARALYSED = 5,
    HASTED = 6,
    IN_COMBAT = 7,
    DROWNING = 8,
    FREEZING = 9,
    DAZZLED = 10,
    CURSED = 11,
    STRENGTHENED = 12,
	PZ_BLOCK = 13,
    IN_PROTECTION_ZONE = 14,
    BLEEDING = 15,
	LESSER_HEX = 16,
	INTENSE_HEX = 17,
	GREATER_HEX = 18,
    ROOTED = 19,
	FEARED = 20,
	GOSHNAR_TAINT_1 = 21,
	GOSHNAR_TAINT_2 = 22,
	GOSHNAR_TAINT_3 = 23,
	GOSHNAR_TAINT_4 = 24,
	GOSHNAR_TAINT_5 = 25,
	NEW_MANA_SHIELD = 26,
	AGONY = 27,
	POWERLESS = 28,
	MENTOR_OTHER = 29,
	COUNT = 30
}

-- Equipment slot indices
EquipmentSlot = {
    NONE = 0,
    HELMET = 1,
    AMULET = 2,
    BACKPACK = 3,
    ARMOR = 4,
    RIGHT_HAND = 5,
    LEFT_HAND = 6,
    LEGS = 7,
    BOOTS = 8,
    RING = 9,
    ARROW = 10,
    STORE = 11
}

-- Player skull types
Skull = {
    NO_SKULL = 0,
    YELLOW = 1,
    GREEN = 2,
    WHITE = 3,
    RED = 4,
    BLACK = 5,
    REVENGE = 6
}

-- Fight stance modes
FightMode = {
    UNKNOWN = 0,
    OFFENSIVE = 1,
    BALANCED = 2,
    DEFENSIVE = 3
}

-- creature chase modes
ChaseMode = {
    STAND = 0,
    CHASE = 1,
    UNKNOWN = 2
}

-- Player-versus-player modes
PVPMode = {
    WHITE_DOVE = 0,
    WHITE_HAND = 1,
    YELLOW_HAND = 2,
    RED_FIST = 3,
    UNKNOWN = 4
}

-- creature icon modifications (e.g., fiendish)
CreatureIcon = {
    NONE = 0,
    WEAKENED = 1,
    LOWER_DAMAGE = 2,
    TURNED_MELEE = 3,
    INFLUENCED = 4,
    FIENDISH = 5,
    REDUCED_HEALTH = 6
}

-- Player and monster skill identifiers
Skill = {
    NONE = 0,
    EXPERIENCE = 1,
    LEVEL = 2,
    EXPERIENCE_GAIN = 3,
    MAGIC_LEVEL = 4,
    HIT_POINTS = 6,
    MANA = 7,
    SPEED = 8,
    CAPACITY = 9,
    SHIELDING = 10,
    DISTANCE = 11,
    CLUB = 12,
    SWORD = 13,
    AXE = 14,
    FIST = 15,
    FISHING = 16,
    FOOD = 17,
    SOUL = 18,
    STAMINA = 19,
    OFFLINE_TRAINING = 20,
    CRITICAL_CHANCE = 21,
    CRITICAL_EXTRA_DAMAGE = 22,
    LIFE_LEECH_CHANCE = 23,
    LIFE_LEECH_AMOUNT = 24,
    MANA_LEECH_CHANCE = 25,
    MANA_LEECH_AMOUNT = 26,
    ONSLAUGHT_LEVEL = 27,
    RUSE_LEVEL = 28,
    MOMENTUM_LEVEL = 29,
    CLEAVE_PERCENTAGE = 30,
    MAGIC_SHIELD_FLAT = 31,
    MAGIC_SHIELD_PERCENT = 32,
    PERFECT_SHOT_DAMAGE = 33,
    DAMAGE_REFLECTION = 36
}

-- vip list icon flags
VipFlag = {
    NO_FLAG = 0,
    HEART = 1,
    SKULL_CROSSED = 2,
    THUNDER = 3,
    AIM_TARGET = 4,
    STAR = 5,
    YING_YANG = 6,
    GREEN_TRIANGLE = 7,
    CROSS = 8,
    MONEY_SIGN = 9,
    GREEN_TARGET = 10
}

Vocation = {
	VOCATION_KNIGHT_CIP = 1,
	VOCATION_PALADIN_CIP = 2,
	VOCATION_SORCERER_CIP = 3,
	VOCATION_DRUID_CIP = 4,
	VOCATION_MONK_CIP = 5
}

CreatureType = {
	CREATURETYPE_PLAYER = 0,
	CREATURETYPE_MONSTER = 1,
	CREATURETYPE_NPC = 2,
	CREATURETYPE_SUMMON_OWN = 3,
	CREATURETYPE_SUMMON_OTHERS = 4,
	CREATURETYPE_HIDDEN = 5,
}

WalkerEvent = {
    -- Fired when the walker reaches a 'Label' waypoint.
    -- Legacy blocking handler. Prefer OBSERVE_LABEL for telemetry.
    ON_LABEL = 0,

    -- Non-blocking. Fired when the selected waypoint changes.
    ON_WAYPOINT_CHANGE = 1,

    -- Fired when the walker executes an 'Action' waypoint.
    -- Legacy blocking handler. Prefer OBSERVE_ACTION for telemetry.
    ON_ACTION = 2,

    -- Non-blocking label observer.
    OBSERVE_LABEL = 3,

    -- Non-blocking observer fired when an Action waypoint is reached, before
    -- any legacy interceptor finishes. Prefer ACTION_STARTED/ACTION_COMPLETED
    -- when the real execution lifecycle matters.
    OBSERVE_ACTION = 4,

    -- Non-blocking. Fired once when an Action actually starts executing.
    ACTION_STARTED = 5,

    -- Non-blocking. Fired once with the terminal result of a started Action.
    ACTION_COMPLETED = 6,

    -- Non-blocking movement packet observers.
    MOVEMENT_CONFIRMED = 7,
    MOVEMENT_REJECTED = 8,
}

-- Feature-mask bits used by Walker Special Areas. Combine individual values
-- when one rectangle should disable multiple cavebot features.
SpecialAreaFeature = {
    Walker = 1,
    Targeting = 2,
    MagicShooter = 4,
    Looter = 8,
    All = 15
}



